
services:
  
  app:
    container_name: totem-pedidos-app
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    pull_policy: build
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_URL=postgresql://totempedidos:totempedidos@db:5432/totempedidos
    networks:
      - app-network

  db:
    container_name: totem-pedidos-db
    image: postgres:latest
    environment:
      - POSTGRES_USER=totempedidos
      - POSTGRES_PASSWORD=totempedidos
      - POSTGRES_DB=totempedidos
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  db_data:
    driver: local

networks:
  app-network:
    driver: bridge