
services:
  
  app:
    container_name: totem-pedidos-app
    build:
      context: .
      dockerfile: Dockerfile
    pull_policy: build
    ports:
      - "8080:8080"
    environment:
      - DB_DRIVER=postgres
      - DB_USER=totempedidos
      - DB_PASS=totempedidos
      - DB_HOST=db:5432
      - DB_NAME=totempedidos
      - DB_OPTIONS=?sslmode=disable
      - SERVER_PORT=8080
    depends_on:
      db:
        condition: service_healthy
    networks:
      - totempedidos-network

  db:
    container_name: totem-pedidos-db
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    volumes:
      - totempedidos-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=totempedidos
      - POSTGRES_PASSWORD=totempedidos
      - POSTGRES_DB=totempedidos
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d totempedidos -U totempedidos"]
      interval: 10s
      timeout: 5s
      retries: 5    
    networks:
      - totempedidos-network

  migration:
    container_name: totem-pedidos-migration
    image: postgres:16-alpine
    command: >
      bash -c "
        sleep 5 &&
        PGPASSWORD=totempedidos psql -h db -U totempedidos -d totempedidos -f /migrations/0001_init.sql &&
        echo 'Migrations executed successfully'"
    volumes:
      - ./migrations:/migrations
    depends_on:
      db:
        condition: service_healthy
    networks:
      - totempedidos-network

networks:
  totempedidos-network:

volumes:
  totempedidos-db:
