alias DescMain = """
**Totem de Pedidos** é um sistema de pedidos para restaurantes, bares e lanchonetes. Ele permite que os clientes façam pedidos diretamente do seu dispositivo móvel, sem precisar esperar por um garçom. O sistema é fácil de usar e pode ser personalizado para atender às necessidades específicas de cada estabelecimento.
""";


alias Info = {
    title: "Totem de Pedidos",
    version: "1.0.0",
    contact: {
        name: "Totem de Pedidos",
        url: "https://totem.mfavl-soat11.software",
    },
    "x-logo": {
        url: "https://avatars.githubusercontent.com/u/206149088?s=200&v=4",
        altText: "FIAP 11SOAT",
    }
};