alias DescMain = """
> **Totem de Pedidos** é um sistema de pedidos para restaurantes, bares e lanchonetes. Ele permite que os clientes façam pedidos diretamente do seu dispositivo móvel, sem precisar esperar por um garçom. O sistema é fácil de usar e pode ser personalizado para atender às necessidades específicas de cada estabelecimento.
""";


alias Info = {
    title: "Totem de Pedidos",
    summary: DescMain,
    version: "1.0.0",
    contact: {
        name: "Melhorzin Key Haven",
        url: "https://totem.mfavl-soat11.software",
    },
    "x-logo": {
        url: "https://redocly.github.io/redoc/museum-logo.png",
        altText: "Logo",
    }
};