openapi: 3.1.0
info:
  title: Totem de Pedidos
  version: 1.0.0
  contact:
    name: Totem de Pedidos
    url: https://totem.mfavl-soat11.software
  x-logo:
    url: https://avatars.githubusercontent.com/u/206149088?s=200&v=4
    altText: FIAP 11SOAT
  description: '**Totem de Pedidos** é um sistema de pedidos para restaurantes, bares e lanchonetes. Ele permite que os clientes façam pedidos diretamente do seu dispositivo móvel, sem precisar esperar por um garçom. O sistema é fácil de usar e pode ser personalizado para atender às necessidades específicas de cada estabelecimento.'
tags:
  - name: Customers
paths:
  /customers:
    get:
      operationId: Customers_getCustomers
      summary: Get all customers
      description: Get all customers
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Customer'
      tags:
        - Customers
    post:
      operationId: Customers_createCustomer
      summary: Create a new customer
      description: Create a new customer
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
      tags:
        - Customers
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                customer:
                  $ref: '#/components/schemas/Customer'
              required:
                - customer
  /customers/{id}:
    get:
      operationId: Customers_getCustomer
      summary: Get a customer by ID
      description: Get a customer by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
      tags:
        - Customers
    delete:
      operationId: Customers_deleteCustomer
      summary: Delete a customer
      description: Delete a customer
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: 'There is no content to send for this request, but the headers may be useful. '
      tags:
        - Customers
components:
  schemas:
    Customer:
      type: object
      required:
        - id
        - name
        - email
      properties:
        id:
          type: string
        name:
          type: string
        email:
          type: string
